### ISSUE TITLE
How do boundary violations pertain to our code?

### ISSUE THREAD

**Issue by thelfenbaum** [laviealon/RoutineOptimizer-SpringBoot#11]
- Step 1: Research more about boundary violations 
- Step 2: Address in code by creating issues and assigning with the 'refactor' tag

**Comment by thelfenbaum** [comment]
after review, we seem to be find and have no boundary violations. However, there are a few lingering questions that I hope to research over the course of today:

1. when are interfaces required for crossing boundaries?
2. are we putting data in and data out in the same use case? this would be an SRP issue
3. who do I delegate choosing MVC vs MVP to?

**Comment by laviealon** [comment]
I am closing this issue since you have successfully split it up into subtasks which can be converted to more specific issues:
1. Once you answer this question, if any action is required, create an issue for it.
2. You've created an issue tackling this so I think we are done with that topic.
3. We will be doing MVC, from the research I've done in light of this question it seems to be the most fitting for our code.
