### ISSUE TITLE
How to create a GUI (which is compatible with SpringBoot)?

### ISSUE THREAD

**Issue by laviealon** [laviealon/RoutineOptimizer-SpringBoot#3]
## Research how to create a GUI that supports the following features: ##

Step 1: research resources
- React:
  https://reactjs.org/docs/create-a-new-react-app.html
  https://www.youtube.com/watch?v=kVeOpcw4GWY
- HTML/CSS/JS:
  https://teamtreehouse.com/community/how-to-create-a-java-web-application-do-i-need-to-first-learn-html-css-javascript
  https://www.coursera.org/learn/html-css-javascript-for-web-developers
  https://www.youtube.com/watch?v=tTNv9i2BgQc
  https://www.youtube.com/watch?v=85tq0LjYATk
  https://www.youtube.com/watch?v=Q33KBiDriJY

Step 2: come up with rough idea for how to design features and eliminate or re-design as needed
1.  Preliminary features:
    - Page 1: home
    - Page 2A (if click sign-in): username and password, have option to sign up
    - Page 2B (if click sign-up): username and password, have option to sign in
    - Page 2C (if click about us): about us
    - Page 3: sidebar with weeks 
2. Advanced features:
    - On page 3, can select a week, and can edit, remove, add tasks; can add project
    - Edit:
        - Change colour
        - Change name 
        - Change duration (by dragging)
        - Change start time (by dragging)
        - Mark as completed (little bar that turns green on top of task)

DO NOT ADD ANY CODE TO PROJECT! THIS ISSUE IS JUST REGARDING RESEARCH!

**Comment by laviealon** [comment]
Found out how to create HTML/CSS components for pages 1, 2A, and 2B. Still need to research JS for these pages (to prompt transitions and feed data into Spring Boot); potentially check out Evan's video/ask Evan.

**Comment by issamarabi** [comment]
We choose HTML

**Comment by issamarabi** [comment]
Step 1 ✅

**Comment by issamarabi** [comment]
Step 2: Part 1 ✅

**Comment by JMH-0402** [comment]
One way that page 3 can be designed is after a week is selected, there is a textfield where the user inputs a task (depending how it is programmed, the input would be something like an id or the name of the task), a dropdown menu that has the option of choosing whether they would like to change the colour or the name of the task. After the user selects the option, they can fill in a textfield where they can input their change. In order to provide the user with the option of completing a task, there can be a button that can be clicked to indicate the task is done and a button that can mark the task as incomplete, where the text can turn green or be encapsulated by a green box if the task is complete. To provide a summary, this design would include selecting a task, then having many options to change the information about the task. 

Create a dropdown: https://blog.hubspot.com/website/html-dropdown
Create a textfield: https://www.w3schools.com/html/html_forms.asp
Encapsulate text in a box: https://www.thesitewizard.com/css/rectangular-box-border.shtml
Make text green: https://www.html.am/html-codes/color/html-green-code.cfm
Creating a Schedule resource: https://www.geeksforgeeks.org/how-to-create-time-table-schedule-using-html/

**Comment by laviealon** [comment]
@Asensio55 - Jeong's comment is a good example of a detailed issue response. I think we are ready to start the GUI and so am closing this issue.
